using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace EternalFS.Generator.Templates;

public class FileTemplate
{
    private readonly string _sourceText;
    
    public string HintName { get; }

    public FileTemplate(string hintName, string sourceText)
    {
        HintName = hintName;
        _sourceText = sourceText;
    }

    public SourceText GetSource()
    {
        return SourceText.From(string.Format(SOURCE_FILE_TEMPLATE, _sourceText), Encoding.UTF8);
    }

    private const string SOURCE_FILE_TEMPLATE = $@"
// <source-generated>
// This code was generated by a source generator.
// Changes to this file may be overwritten on next generation pass.

{{0}}";
}
